name: hiragana_converter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.3.0
  json_annotation: ^4.9.0
  riverpod_annotation: ^2.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.4
  build_runner: ^2.4.15
  custom_lint: ^0.7.3
  riverpod_lint: ^2.6.4

flutter:
  uses-material-design: true
